# Generated by Django 6.0.2 on 2026-02-15 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=30)),
                ('children_status', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('sub_caste', models.CharField(blank=True, max_length=100)),
                ('mother_tongue', models.CharField(max_length=100)),
                ('height_cm', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('annual_income', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('rashi', models.CharField(blank=True, max_length=100)),
                ('manglik', models.BooleanField(default=False)),
                ('anonymous_mode_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
