# Generated by Django 6.0.2 on 2026-02-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='children_status',
            field=models.CharField(choices=[('none', 'No Children'), ('has_children', 'Has Children')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=30),
        ),
    ]
