# Generated by Django 6.0.2 on 2026-02-15 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_children_status_alter_profile_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profiles_pr_user_id_3364d1_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='profiles_pr_gender_fc2e15_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_of_birth'], name='profiles_pr_date_of_6d425e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['religion'], name='profiles_pr_religio_f6b0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['caste'], name='profiles_pr_caste_0e3e99_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'state', 'city'], name='profiles_pr_country_8148f8_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active', 'is_soft_deleted'], name='profiles_pr_is_acti_bd1526_idx'),
        ),
    ]
