# Generated by Django 6.0.2 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profilephoto"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="profilephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile",),
                name="unique_primary_photo_per_profile",
            ),
        ),
    ]
