# Generated by Django 6.0.2 on 2026-02-15 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('rejection_reason_code', models.CharField(blank=True, max_length=50)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interests', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['sender'], name='interests_i_sender__c00945_idx'), models.Index(fields=['receiver'], name='interests_i_receive_2698dd_idx'), models.Index(fields=['status'], name='interests_i_status_644759_idx'), models.Index(fields=['created_at'], name='interests_i_created_43cd86_idx')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
