# Generated by Django 6.0.2 on 2026-02-16 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_matches', to='profiles.profile')),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile1', to='profiles.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile2', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile1'], name='matches_mat_profile_047bec_idx'), models.Index(fields=['profile2'], name='matches_mat_profile_785651_idx'), models.Index(fields=['is_active'], name='matches_mat_is_acti_b1aa79_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile1', 'profile2'), name='unique_match_pair')],
            },
        ),
    ]
